version: '3.4'

services:
  catalogdb:
    image: mongo

  basketdb:
    image: redis:alpine

  discountdb:
    image: postgres

  orderdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

  catalog.api:
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.API/Dockerfile

  discount.api:
    build:
      context: .
      dockerfile: src/Services/Discount/Discount.API/Dockerfile

  discount.grpc:
    build:
      context: .
      dockerfile: src/Services/Discount/Discount.Grpc/Dockerfile

  ordering.api:
    build:
      context: .
      dockerfile: src/Services/Ordering/Ordering.API/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:


